export const sosEmail = (username, location, city, timestamp) => {
  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SOS Emergency Report</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
      background-color: #f9f9f9;
    }
    .container {
      width: 100%;
      max-width: 650px;
      margin: 20px auto;
      background-color: #ffffff;
      padding: 20px;
      border-radius: 8px;
      border: 2px solid #d32f2f;
      box-shadow: 0 0 12px rgba(0,0,0,0.15);
    }
    .header {
      background-color: #d32f2f;
      color: #fff;
      padding: 15px;
      text-align: center;
      border-radius: 6px 6px 0 0;
    }
    .header h2 {
      margin: 0;
      font-size: 22px;
      letter-spacing: 1px;
    }
    .section {
      margin: 20px 0;
    }
    .section h3 {
      margin-bottom: 10px;
      font-size: 18px;
      color: #333;
      border-bottom: 1px solid #ccc;
      padding-bottom: 5px;
    }
    .section p {
      font-size: 15px;
      margin: 6px 0;
      color: #444;
    }
    .highlight {
      background-color: #fff4f4;
      padding: 10px;
      border-left: 4px solid #d32f2f;
      border-radius: 4px;
      margin: 10px 0;
    }
    .footer {
      margin-top: 30px;
      font-size: 13px;
      color: #777;
      text-align: center;
      border-top: 1px solid #eee;
      padding-top: 10px;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h2>🚨 First Information Report (FIR) - SOS Emergency Alert</h2>
    </div>
    
    <div class="section">
      <h3>Complainant Details</h3>
      <p><strong>Name:</strong> ${username}</p>
      <p><strong>City:</strong> ${city}</p>
      <p><strong>Reported At:</strong> ${timestamp}</p>
    </div>

    <div class="section">
      <h3>Incident Location</h3>
      <div class="highlight">
        <p><strong>Latitude:</strong> ${location.latitude}</p>
        <p><strong>Longitude:</strong> ${location.longitude}</p>
      </div>
      <p>This location has been automatically captured by the SOS system. Immediate attention is required.</p>
    </div>

    <div class="section">
      <h3>Nature of Report</h3>
      <p>The SOS system has generated this emergency alert, indicating that the complainant is in distress and requires urgent police intervention.</p>
    </div>

    <div class="footer">
      <p>This FIR-style report has been automatically generated by the Avijo SOS System.</p>
      <p>For official use only.</p>
    </div>
  </div>
</body>
</html>
  `;
};
